Metrics CoinRanking
LarryIVC/react-coins pull request #3
Opened 2023-06-04 01:42 UTC by LarryIVC

### **In this PR, I did the following:**

- [ ]  Create a branch.
- [ ]  Add the Components.
- [ ]  Connect React and Redux.
- [ ]  Handle events in a React app.
- [ ]  Use store, actions, and reducers in React.
- [ ]  Use API to get data and metrics.
- [ ]  Add the logic.
- [ ]  Use styles in a React app.
- [ ]  Add the tests.
- [ ]  Check the linters.

2023-06-04 06:11 UTC, afanimartin requested changes
Hi @LarryIVC, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Remove the back button from the Home page. Clicking on it does nothing and the original design doesn't have it

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-04 06:11 UTC, afanimartin commented on src/components/Details.js
> +  // console.log(coinDetail);
- Please remove this and any comments. Comments make our code ugly

2023-06-04 06:16 UTC, LarryIVC commented on src/components/Details.js
> +  // console.log(coinDetail);
Ok, is it mandatory?
The Microverse time is over.
Thanks, @afanimartin.

2023-06-05 17:17 UTC, LarryIVC commented on src/components/Details.js
> +  // console.log(coinDetail);
## Hi @afanimartin, about the changes required.

> Remove the back button from the Home page. Clicking on it does nothing and the original design doesn't have it

Solved:
Home
![image](https://github.com/LarryIVC/react-coins/assets/110146573/b51f3da6-455a-4367-873c-80fbaaab1590)

Details
![image](https://github.com/LarryIVC/react-coins/assets/110146573/a21959f2-2c19-4778-915b-1bb5a8b14327)

2023-06-05 17:56 UTC, julie-ify approved these changes
Hi @LarryIVC,

## Highlights!
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working routes ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 20:08 UTC, merged